name: CI -> Deploy to My website
on:
  push:
    branches: kalhel96-patch-1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Here is the deployment action
      - name: Upload from public_html via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          lftp_settings: "set net:max-retries 5; set net:persist-retries 10; set net:timeout 60s;"
          # local_dir: "/home/kaleabdenboba/public_html/kaleabdenboba.com/kalgech"
